### ISSUE TITLE
Deliverable 1 - Inception

### ISSUE THREAD

**Issue by csaluski** [Csaluski/cs-386-project#10]
Deliverable 1 involves reporting on the basic idea of the software, its value proposition and target customer segments, and conducting interviews to refine the requirements. 
1. [ ] Introduction
2. [ ] Initial value proposition + customer segments
3. [ ] Interviews summary
4. [ ] Final value proposition
5. [ ] Interviews

[D1. Inception(2).pdf](https://github.com/Csaluski/cs-386-project/files/6794644/D1.Inception.2.pdf)

**Comment by phase** [comment]
I can do the final Markdown formatting for the whole document. I believe he wants all of the interview summaries stitched together along with the other sections you mentioned.
