### ISSUE TITLE
Conduct interviews

### ISSUE THREAD

**Issue by csaluski** [Csaluski/cs-386-project#9]
We need at minimum 10 interviews done.

**Comment by csaluski** [comment]
1/10 "mock" interview was conducted with Hannah's significant other during meeting today, for Jadon to write up.

**Comment by csaluski** [comment]
I have two or three interviews scheduled for tomorrow, 3/10 or 4/10.

**Comment by jboal-trinity** [comment]
I have 2  more today and  1 tonight/tommorrow
